name: typecho
services:
  typecho:
    image: joyqi/typecho:nightly-php7.4-apache
    container_name: typecho
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 80
      published: '8080'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/typecho
      target: /app/usr
    environment:
      TYPECHO_SITE_URL: https://your-domain.com
