name: linkstack
services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    environment:
      TZ: Europe/Berlin
      SERVER_ADMIN: admin@example.com
      HTTP_SERVER_NAME: example.com
      HTTPS_SERVER_NAME: example.com
      LOG_LEVEL: info
      PHP_MEMORY_LIMIT: 256M
      UPLOAD_MAX_FILESIZE: 8M
    ports:
    - target: 80
      published: '8081'
      protocol: tcp
    restart: unless-stopped
    container_name: linkstack
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
