name: firefox
services:
  firefox:
    container_name: firefox
    image: linuxserver/firefox:latest
    deploy:
      resources:
        reservations:
          memory: 768M
    environment:
    - DOCKER_MODS=linuxserver/mods:universal-package-install
    - FIREFOX_CLI=https://www.google.com/
    - INSTALL_PACKAGES=font-noto-cjk
    - LC_ALL=zh_CN.UTF-8
    - CUSTOM_USER=admin
    - PASSWORD=admin
    - PGID=1000
    - PUID=1000
    - TZ=Asia/Shanghai
    - NO_DECOR=1
    hostname: firefox
    ports:
    - target: 3000
      published: '3000'
      protocol: tcp
    - target: 3001
      published: '3001'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/firefox/config
      target: /config
    network_mode: bridge
    privileged: false
