name: linuxserver-htpcmanager
services:
  app:
    image: linuxserver/htpcmanager:version-26a641bf
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 8085
      published: 8085
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/htpcmanager/config
      target: /config
