name: linuxserver-flexget
services:
  app:
    image: linuxserver/flexget:3.20.14
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FG_LOG_LEVEL: ''
      FG_LOG_FILE: ''
      FG_CONFIG_FILE: ''
      FG_WEBUI_PASSWORD: ''
    ports:
    - target: 5050
      published: 5050
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/flexget/config
      target: /config
    - type: bind
      source: /DATA/AppData/flexget/data
      target: /data
