name: linuxserver-doplarr_rs
services:
  app:
    image: linuxserver/doplarr_rs:4.6.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/doplarr_rs/config
      target: /config
