name: linuxserver-phpmyadmin
services:
  app:
    image: linuxserver/phpmyadmin:5.2.3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PMA_ARBITRARY: ''
      PMA_ABSOLUTE_URI: ''
      PMA_HOST: 172.17.0.1
      PMA_USER: saturn
      PMA_PASSWORD: saturn
    ports:
    - target: 8081
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/phpmyadmin/config
      target: /config
