name: excalidraw
services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    deploy:
      resources:
        reservations:
          memory: 256M
    restart: unless-stopped
    ports:
    - target: 80
      published: '17638'
      protocol: tcp
