name: stash
services:
  stash:
    image: stashapp/stash:latest
    deploy:
      resources:
        reservations:
          memory: 128M
    container_name: stash
    restart: unless-stopped
    ports:
    - 9999:9999
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 2m
    environment:
    - STASH_STASH=/data/
    - STASH_GENERATED=/generated/
    - STASH_METADATA=/metadata/
    - STASH_CACHE=/cache/
    - STASH_PORT=9999
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /DATA/AppData/stash/config:/root/.stash
    - /DATA/AppData/stash/data:/data
    - /DATA/AppData/stash/metadata:/metadata
    - /DATA/AppData/stash/cache:/cache
    - /DATA/AppData/stash/blobs:/blobs
    - /DATA/AppData/stash/generated:/generated
