name: sscms
services:
  sscms:
    image: sscms/core:latest
    container_name: sscms
    restart: unless-stopped
    ports:
    - 8081:80
    volumes:
    - /DATA/AppData/sscms/wwwroot:/app/wwwroot
    environment:
      SSCMS_SECURITY_KEY: e2a3d303-ac9b-41ff-9154-930710af0845
      SSCMS_DATABASE_TYPE: SQLite
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
