name: linuxserver-synclounge
services:
  app:
    image: linuxserver/synclounge:5.2.35
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    ports:
    - target: 8088
      published: 8088
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/synclounge/config
      target: /config
