name: photoprism-arm
services:
  photoprism-arm:
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: saturn
      PHOTOPRISM_UPLOAD_NSFW: 'true'
      TZ: $TZ
    image: photoprism/photoprism:231011-armv7
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    ports:
    - target: 2342
      published: '2342'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/photoprism-arm/photoprism/storage
      target: /photoprism/storage
    - type: bind
      source: /DATA/Gallery
      target: /photoprism/originals
    container_name: photoprism-arm
