name: emulatorjs-arm
services:
  emulatorjs-arm:
    environment:
    - PGID=$PGID
    - PUID=$PUID
    - SUBFOLDER=/
    - TZ=$TZ
    image: lscr.io/linuxserver/emulatorjs:arm32v7-1.7.2
    network_mode: bridge
    ports:
    - target: 3000
      published: '3001'
      protocol: tcp
    - target: 4001
      published: '4001'
      protocol: tcp
    - target: 80
      published: '88'
      protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/emulatorjs-arm/config
      target: /config
    - type: bind
      source: /DATA/AppData/emulatorjs-arm/data
      target: /data
    - type: bind
      source: /ROMS/nes
      target: /data/nes/roms
    container_name: emulatorjs-arm
