name: netronome
services:
  netronome:
    image: ghcr.io/autobrr/netronome:v0.13.0
    container_name: netronome
    restart: unless-stopped
    entrypoint:
    - /sbin/tini
    - --
    - /bin/sh
    - -c
    command:
    - "config=/data/.config/netronome/config.toml\nif [ ! -f \"$$config\" ]; then\n\
      \  netronome generate-config\nfi\nexec netronome serve"
    ports:
    - target: 7575
      published: '7575'
      protocol: tcp
    environment:
      TZ: $TZ
      NETRONOME__HOST: 0.0.0.0
      NETRONOME__PORT: 7575
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    cap_add:
    - NET_RAW
