name: kplayer
services:
  kplayer:
    image: bytelang/kplayer:latest
    container_name: kplayer
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 4156
      published: '4156'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/kplayer/cache
      target: /kplayer/cache
    - type: bind
      source: /DATA/AppData/kplayer/config.json
      target: /kplayer/config.json
    - type: bind
      source: /media
      target: /media
    - type: bind
      source: /mnt
      target: /mnt
