name: linuxserver-nzbget
services:
  app:
    image: linuxserver/nzbget:26.3.20260911
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      NZBGET_USER: ''
      NZBGET_PASS: ''
    ports:
    - target: 6789
      published: 6789
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/nzbget/config
      target: /config
    - type: bind
      source: /DATA/AppData/nzbget/downloads
      target: /downloads
