name: big-bear-adguard-home-host
services:
  big-bear-adguard-home-host:
    container_name: big-bear-adguard-home-host
    image: adguard/adguardhome:v0.107.78@sha256:1ea34eafe5dc691007946e8eaab7bf46b0de9412f39213d8c06e48b53bf9a6c5
    volumes:
    - /DATA/AppData/$AppID/data/work:/opt/adguardhome/work
    - /DATA/AppData/$AppID/data/conf:/opt/adguardhome/conf
    restart: unless-stopped
    network_mode: host
