name: nextchat
services:
  nextchat:
    container_name: nextchat
    image: yidadaa/chatgpt-next-web
    deploy:
      resources:
        reservations:
          memory: 64M
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    environment:
    - OPENAI_API_KEY=$OPENAI_API_KEY
    - CODE=password1,password2,password3
    - BASE_URL=https://api.openai.com
    network_mode: bridge
