version: '3.3'
name: fastgpt
services:
  pg:
    image: ankane/pgvector:v0.5.0
    container_name: pg
    restart: unless-stopped
    ports:
    - 5432:5432
    networks:
    - fastgpt
    environment:
    - POSTGRES_USER=username
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    volumes:
    - /DATA/AppData/fastgpt/pg/data:/var/lib/postgresql/data
  mongo:
    image: mongo:5.0.18
    container_name: mongo
    restart: unless-stopped
    ports:
    - 27017:27017
    networks:
    - fastgpt
    environment:
    - MONGO_INITDB_ROOT_USERNAME=username
    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - /DATA/AppData/fastgpt/mongo/data:/data/db
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:latest
    ports:
    - 3000:3000
    networks:
    - fastgpt
    depends_on:
    - mongo
    - pg
    restart: unless-stopped
    environment:
    - DEFAULT_ROOT_PSW=1234
    - OPENAI_BASE_URL=https://api.openai.com/v1
    - CHAT_API_KEY=sk-xxxx
    - DB_MAX_LINK=5
    - TOKEN_KEY=any
    - ROOT_KEY=root_key
    - FILE_TOKEN_KEY=filetoken
    - MONGODB_URI=mongodb://username:password@mongo:27017/fastgpt?authSource=admin
    - PG_URL=postgresql://username:password@pg:5432/postgres
    volumes:
    - /DATA/AppData/fastgpt/config.json:/app/data/config.json
networks:
  fastgpt:
    name: fastgpt
