name: joomla
services:
  app:
    image: joomla:5.4.8-apache
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: saturn
    depends_on:
    - joomladb
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/www
      target: /var/www/html
  joomladb:
    image: mysql:9.7.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: saturn
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/mysql
      target: /var/lib/mysql
