name: draw.io
services:
  app:
    image: jgraph/drawio:21.7.5
    restart: unless-stopped
    environment:
      LETS_ENCRYPT_ENABLED: false
      PUBLIC_DNS: ''
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/log/letsencrypt
      target: /var/log/letsencrypt
    - type: bind
      source: /DATA/AppData/$AppID/letsencrypt
      target: /etc/letsencrypt
    - type: bind
      source: /DATA/AppData/$AppID/lib/letsencrypt
      target: /var/lib/letsencrypt
