name: 1panel
services:
  1panel:
    container_name: 1panel
    deploy:
      resources:
        reservations:
          memory: 512M
    environment:
    - TZ=Asia/Shanghai
    hostname: 1panel
    image: moelin/1panel:latest
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/volumes:/var/lib/docker/volumes
    - /DATA/AppData/1panel/opt:/opt
    - /DATA/AppData/1panel/root:/root
    labels:
      createdBy: Apps
    network_mode: host
    privileged: false
