name: lucky
services:
  lucky:
    image: gdy666/lucky:v2
    container_name: lucky
    restart: unless-stopped
    network_mode: host
    volumes:
    - /DATA/AppData/lucky:/app/conf
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          memory: 64M
