name: cups
services:
  cups:
    image: anujdatar/cups:latest
    container_name: cups
    devices:
    - /dev/bus/usb:/dev/bus/usb
    environment:
      CUPSADMIN: admin
      CUPSPASSWORD: password
      TZ: Asia/Shanghai
    network_mode: bridge
    ports:
    - 631:631
    volumes:
    - /DATA/AppData/cups/config:/etc/cups
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    deploy:
      resources:
        reservations:
          memory: 64M
