name: flare
services:
  flare:
    image: soulteary/flare:latest
    deploy:
      resources:
        reservations:
          memory: 32M
    network_mode: bridge
    ports:
    - target: 5005
      published: '5005'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/flare
      target: /app
    container_name: flare
