name: kavita
services:
  app:
    image: jvmilazz0/kavita:0.9.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/manga
      target: /manga
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /kavita/config
