name: dsh-harness
services:
  dsh:
    command: null
    container_name: dsh-harness
    entrypoint: null
    image: ghcr.io/smanx/deepseek-harness:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/deepseek.png
    networks:
    - default
    ports:
    - mode: ingress
      target: 3080
      published: '3080'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID
      target: /root/.dsh
      bind:
        create_host_path: true
