name: ntfy
services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
    - serve
    environment:
    - TZ=UTC
    volumes:
    - /DATA/AppData/ntfy/cache:/var/cache/ntfy
    - /DATA/AppData/ntfy/config:/etc/ntfy
    ports:
    - target: 80
      published: '3380'
      protocol: tcp
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
