name: xunlei
services:
  xunlei:
    image: registry.cn-shenzhen.aliyuncs.com/cnk3x/xunlei:latest
    container_name: xunlei
    deploy:
      resources:
        reservations:
          memory: 128M
    privileged: true
    network_mode: bridge
    ports:
    - 2345:2345
    environment:
      XL_DASHBOARD_PORT: '2345'
      XL_DASHBOARD_USERNAME: admin
      XL_DASHBOARD_PASSWORD: admin
      XL_DIR_DOWNLOAD: /xunlei/downloads
      XL_DIR_DATA: /xunlei/data
    volumes:
    - type: bind
      source: /DATA/AppData/xunlei/data
      target: /xunlei/data
    - type: bind
      source: /DATA/Downloads/ThunderDownloads
      target: /xunlei/downloads
    - type: bind
      source: /mnt
      target: /xunlei/HDD
    - type: bind
      source: /media/devmon
      target: /xunlei/UDISK
    restart: unless-stopped
