name: prowlarr-arm
services:
  prowlarr-arm:
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: linuxserver/prowlarr:arm32v7-1.5.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 9696
      published: '9696'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/prowlarr/config
      target: /config
    container_name: prowlarr-arm
