name: linuxserver-opera
services:
  app:
    image: linuxserver/opera:135.0.5973
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      OPERA_CLI: ''
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    - target: 3001
      published: 3001
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/opera/config
      target: /config
