name: linuxserver-feed2toot
services:
  app:
    image: linuxserver/feed2toot:0.17.20250110
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FEED_LIMIT: ''
    volumes:
    - type: bind
      source: /DATA/AppData/feed2toot/config
      target: /config
