name: quark-auto-save
services:
  quark-auto-save:
    image: registry.cn-shenzhen.aliyuncs.com/cp0204/quark-auto-save:latest
    container_name: quark-auto-save
    deploy:
      resources:
        reservations:
          memory: 32M
    network_mode: bridge
    ports:
    - target: 5005
      published: '5005'
      protocol: tcp
    restart: unless-stopped
    environment:
      WEBUI_USERNAME: admin
      WEBUI_PASSWORD: admin123
    volumes:
    - type: bind
      source: /DATA/AppData/quark-auto-save/config
      target: /app/config
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
