name: maxkb
services:
  maxkb:
    image: cr2.fit2cloud.com/1panel/maxkb:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 2048M
    ports:
    - 18080:8080
    volumes:
    - type: bind
      source: /DATA/AppData/maxkb/data
      target: /var/lib/postgresql/data
    container_name: maxkb
    network_mode: bridge
