name: matter-server
services:
  app:
    image: ghcr.io/home-assistant-libs/python-matter-server:8.1
    restart: unless-stopped
    network_mode: host
    volumes:
    - type: bind
      source: /DATA/AppData/matter-server/data
      target: /data
    - type: bind
      source: /run/dbus
      target: /run/dbus
      read_only: true
    security_opt:
    - apparmor:unconfined
