name: open-webui
services:
  open-webui:
    container_name: open-webui
    deploy:
      resources:
        reservations:
          memory: 1024M
    hostname: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
    - 3000:8080
    restart: unless-stopped
    volumes:
    - /DATA/AppData/ollama:/root/.ollama
    - /DATA/AppData/open-webui:/app/backend/data
    network_mode: bridge
    privileged: false
