name: gateway-go
services:
  gateway-go:
    image: openiothub/gateway-go:v2.0.12
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 32M
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/saturn-AppStore@main/Apps/Gateway-go/icon.svg
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /root
    ports:
    - target: 34323
      published: '34323'
      protocol: tcp
    container_name: gateway-go
