name: teslamate
services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: unless-stopped
    environment:
    - ENCRYPTION_KEY=secretkey
    - DATABASE_USER=teslamate
    - DATABASE_PASS=teslamate
    - DATABASE_NAME=teslamate
    - DATABASE_HOST=database
    - MQTT_HOST=mosquitto
    ports:
    - published: '4000'
      target: 4000
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/teslamate/import
      target: /opt/app/import
    cap_drop:
    - all
    container_name: teslamate
    deploy:
      resources:
        reservations:
          memory: 1024M
    networks:
    - teslamate
  database:
    image: postgres:16
    restart: unless-stopped
    environment:
    - POSTGRES_USER=teslamate
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=teslamate
    volumes:
    - type: bind
      source: /DATA/AppData/teslamate/db
      target: /var/lib/postgresql/data
    container_name: teslamate-db
    networks:
    - teslamate
  grafana:
    image: teslamate/grafana:latest
    restart: unless-stopped
    environment:
    - DATABASE_USER=teslamate
    - DATABASE_PASS=teslamate
    - DATABASE_NAME=teslamate
    - DATABASE_HOST=database
    ports:
    - published: '3001'
      target: 3000
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/teslamate/grafana-data
      target: /var/lib/grafana
    container_name: teslamate-grafana
    networks:
    - teslamate
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
    - type: bind
      source: /DATA/AppData/teslamate/mosquitto/conf
      target: /mosquitto/config
    - type: bind
      source: /DATA/AppData/teslamate/mosquitto/data
      target: /mosquitto/data
    container_name: teslamate-mosquitto
    networks:
    - teslamate
networks:
  teslamate:
    name: teslamate
