name: statping
services:
  app:
    image: statping/statping:v0.90.74
    restart: always
    depends_on:
    - db
    environment:
      VIRTUAL_PORT: 8080
      DB_CONN: postgres
      DB_HOST: db
      DB_USER: saturn
      DB_PASS: saturn
      DB_DATABASE: saturn
      NAME: ''
      DESCRIPTION: ''
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/app
      target: /app
  db:
    image: postgres:15.19
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      POSTGRES_USER: saturn
      POSTGRES_PASSWORD: saturn
      POSTGRES_DB: saturn
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/postgres/data
      target: /var/lib/postgresql/data
