name: ghost
services:
  app:
    image: ghost:6.64.0
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: saturn
      database__connection__password: saturn
      database__connection__database: saturn
    ports:
    - target: 2368
      published: 2368
      protocol: tcp
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - type: bind
      source: /DATA/AppData/ghost/content
      target: /var/lib/ghost/content
  db:
    image: mariadb:13.0.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: saturn
      MYSQL_DATABASE: saturn
      MYSQL_USER: saturn
      MYSQL_PASSWORD: saturn
    volumes:
    - type: bind
      source: /DATA/AppData/ghost/mysql
      target: /var/lib/mysql
    healthcheck:
      test:
      - CMD
      - healthcheck.sh
      - --connect
      - --innodb_initialized
      interval: 10s
      timeout: 5s
      retries: 3
