name: homebridge
services:
  app:
    image: oznu/homebridge:2023-01-08
    restart: unless-stopped
    environment:
      PGID: $PGID
      PUID: $PUID
      ENABLE_AVAHI: 1
      TZ: $TZ
    network_mode: host
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /homebridge
