name: linuxserver-weixin
services:
  app:
    image: linuxserver/weixin:version-f1376de7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    - target: 3001
      published: 3001
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/weixin/config
      target: /config
