name: showdoc
services:
  showdoc:
    container_name: showdoc
    user: root
    restart: unless-stopped
    network_mode: bridge
    privileged: true
    ports:
    - 4999:80
    volumes:
    - /DATA/AppData/showdoc/html:/var/www/html/
    image: star7th/showdoc:arm-latest
    deploy:
      resources:
        reservations:
          memory: 64M
