name: bilibilitoolpro
services:
  bilibilitoolpro:
    environment:
      Ray_DailyTaskConfig__AutoChargeUpId: '-1'
      Ray_DailyTaskConfig__Cron: 0 15 * * *
      Ray_LiveLotteryTaskConfig__Cron: 0 22 * * *
      Ray_UnfollowBatchedTaskConfig__Cron: 0 6 1 * *
      Ray_VipBigPointConfig__Cron: 7 1 * * *
    image: ghcr.io/raywangqvq/bilibili_tool_pro:latest
    container_name: bilibilitoolpro
    network_mode: bridge
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/bilibilitoolpro/cookies.json
      target: /app/cookies.json
    - type: bind
      source: /DATA/AppData/bilibilitoolpro/Logs
      target: /app/Logs
