name: linuxserver-ffmpeg
services:
  app:
    image: linuxserver/ffmpeg:8.1.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/ffmpeg/config
      target: /config
