name: pdfmathtranslate-next
services:
  pdfmathtranslate-next:
    image: awwaawwa/pdfmathtranslate-next:latest
    container_name: pdfmathtranslate-next
    network_mode: bridge
    ports:
    - 7860:7860
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 1024M
