name: mariadb
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
    ports:
    - target: 3306
      published: '3306'
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/mariadb/config
      target: /etc/mysql/conf.d
    - type: bind
      source: /DATA/AppData/mariadb/data
      target: /var/lib/mysql
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
