name: tandoor
services:
  app:
    image: vabene1111/recipes:2
    restart: unless-stopped
    environment:
      SECRET_KEY: ''
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: saturn
      POSTGRES_PASSWORD: saturn
      POSTGRES_DB: saturn
    depends_on:
    - db
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/config
      target: /config
    - type: bind
      source: /DATA/AppData/$AppID/staticfiles
      target: /opt/recipes/staticfiles
    - type: bind
      source: /DATA/AppData/$AppID/mediafiles
      target: /opt/recipes/mediafiles
  db:
    image: postgres:15.19
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      POSTGRES_USER: saturn
      POSTGRES_PASSWORD: saturn
      POSTGRES_DB: saturn
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/postgres/data
      target: /var/lib/postgresql/data
