name: psitransfer
services:
  psitransfer:
    image: psitrax/psitransfer:v2.4.1
    container_name: psitransfer
    ports:
    - target: '3000'
      published: '13001'
      protocol: tcp
    environment:
      PSITRANSFER_ADMIN_PASS: secret
    volumes:
    - type: bind
      source: /DATA/AppData/$AppID/data
      target: /data
    deploy:
      resources:
        reservations:
          memory: 256M
    restart: unless-stopped
