name: linuxserver-ddclient
services:
  app:
    image: linuxserver/ddclient:4.0.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/ddclient/config
      target: /config
