name: linuxserver-socket-proxy
services:
  app:
    image: linuxserver/socket-proxy:3.4.4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/socket-proxy/config
      target: /config
