name: moviepilot
services:
  moviepilot:
    stdin_open: true
    tty: true
    container_name: moviepilot
    hostname: moviepilot
    ports:
    - target: 3000
      published: '3000'
      protocol: tcp
    volumes:
    - /DATA/Media:/media
    - /DATA/AppData/moviepilot/config:/config
    - /DATA/AppData/moviepilot/core:/moviepilot/.cache/ms-playwright
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - NGINX_PORT=3000
    - PORT=3001
    - PUID=0
    - PGID=0
    - UMASK=000
    - TZ=Asia/Shanghai
    - AUTH_SITE=iyuu
    - IYUU_SIGN=xxxx
    - SUPERUSER=admin
    - API_TOKEN=moviepilot
    restart: unless-stopped
    image: jxxghp/moviepilot:latest
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
