name: clouddrive
services:
  clouddrive:
    image: cloudnas/clouddrive2
    container_name: clouddrive
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: host
    pid: host
    privileged: true
    restart: unless-stopped
    volumes:
    - /DATA/AppData/clouddrive/Config:/Config
    - /mnt:/mnt:shared
    - /media:/media:shared
    devices:
    - /dev/fuse:/dev/fuse
    environment:
      CLOUDDRIVE_HOME: /Config
      TZ: Asia/Shanghai
