name: linuxserver-nzbhydra2
services:
  app:
    image: linuxserver/nzbhydra2:8.9.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 5076
      published: 5076
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/nzbhydra2/config
      target: /config
    - type: bind
      source: /DATA/AppData/nzbhydra2/downloads
      target: /downloads
