name: music-tag-web
services:
  music-tag-web:
    image: xhongc/music_tag_web:latest
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
    ports:
    - target: 8001
      published: '8001'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/music-tag-web/media
      target: /app/media
    - type: bind
      source: /DATA/AppData/music-tag-web/config
      target: /app/data
    container_name: music-tag-web
