name: linuxserver-kali-linux
services:
  app:
    image: linuxserver/kali-linux:version-45f3494e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    - target: 3001
      published: 3001
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/kali-linux/config
      target: /config
