name: linuxserver-raneto
services:
  app:
    image: linuxserver/raneto:0.18.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/raneto/config
      target: /config
