name: dweebui
services:
  dweebui:
    container_name: dweebui
    image: lllllllillllllillll/dweebui:latest
    environment:
      PORT: '8000'
      SECRET: MrWiskers
    restart: unless-stopped
    ports:
    - published: '8000'
      target: 8000
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/dweebui/config
      target: /app/config
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    network_mode: bridge
    deploy:
      resources:
        reservations:
          memory: 64M
