name: linuxserver-ombi
services:
  app:
    image: linuxserver/ombi:4.53.10
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
    ports:
    - target: 3579
      published: 3579
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/ombi/config
      target: /config
