name: hivisionidphoto
services:
  hivisionidphoto:
    image: linzeyi/hivision_idphotos:latest
    ports:
    - 7860:7860
    deploy:
      resources:
        reservations:
          memory: 512M
    network_mode: bridge
    restart: unless-stopped
    container_name: hivisionidphoto
