name: aria2
services:
  aria2:
    image: johngong/aria2:latest
    container_name: aria2
    deploy:
      resources:
        reservations:
          memory: 64M
    restart: unless-stopped
    network_mode: bridge
    ports:
    - 6881:6881
    - 6881:6881/udp
    - 6800:6800
    - 6880:8080
    environment:
    - ARIA2_RPC_SECRET=token
    - ARIA2_RPC_LISTEN_PORT=6800
    - ARIA2_LISTEN_PORT=6881
    - UID=1000
    - GID=1000
    - UMASK=022
    volumes:
    - /DATA/AppData/aria2/config:/config
    - /DATA/Downloads:/Downloads
