name: jackett-arm
services:
  jackett-arm:
    environment:
      AUTO_UPDATE: 'true'
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: linuxserver/jackett:arm32v7-0.21.352
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 9117
      published: '9117'
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/jackett-arm/config
      target: /config
    - type: bind
      source: /DATA/Downloads
      target: /downloads
    container_name: jackett-arm
