id: esphome
name: ESPHome
tagline: Home Automation systems
description: ESPHome is a system to control your microcontrollers by simple yet powerful
  configuration files and control them remotely through Home Automation systems.
category: Home
version: 1.0.0
developer: kd9lsv
store: official
icon: icon.png
port: 6052
architectures:
- amd64
- arm64
