name: linuxserver-bazarr
services:
  app:
    image: linuxserver/bazarr:1.6.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 6767
      published: 6767
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/bazarr/config
      target: /config
    - type: bind
      source: /DATA/AppData/bazarr/movies
      target: /movies
    - type: bind
      source: /DATA/AppData/bazarr/tv
      target: /tv
