name: lucky
services:
  lucky:
    deploy:
      resources:
        reservations:
          memory: 64M
    image: gdy666/lucky:2.27.2
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/lucky
      target: /goodluck
    environment:
      TZ: $TZ
    network_mode: host
    privileged: false
