name: smartstrm
services:
  smartstrm:
    image: cp0204/smartstrm:latest
    container_name: smartstrm
    restart: unless-stopped
    network_mode: host
    volumes:
    - /DATA/AppData/smartstrm/config:/app/config
    - /DATA/AppData/smartstrm/logs:/app/logs
    - /DATA/AppData/smartstrm/strm:/strm
    - /DATA/AppData/smartstrm/tools:/app/tools
    environment:
    - PORT=8024
    - ADMIN_USERNAME=admin
    - ADMIN_PASSWORD=admin123
    deploy:
      resources:
        reservations:
          memory: 128M
