name: excalidraw
services:
  excalidraw:
    environment:
      TZ: $TZ
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 80
      published: '5000'
      protocol: tcp
    restart: unless-stopped
