name: one-api
services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    environment:
      TZ: Asia/Shanghai
    volumes:
    - type: bind
      source: /DATA/AppData/one-api/data
      target: /data
    ports:
    - target: 3000
      published: '3000'
      protocol: tcp
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 128M
    network_mode: bridge
