name: linuxserver-shotcut
services:
  app:
    image: linuxserver/shotcut:26.8.1
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    - target: 3001
      published: 3001
      protocol: tcp
    volumes:
    - type: bind
      source: /DATA/AppData/shotcut/config
      target: /config
