name: tailscaled
services:
  tailscaled:
    cap_add:
    - NET_ADMIN
    - NET_RAW
    environment:
      TS_EXTRA_ARGS: --advertise-exit-node
      TS_ROUTES: 192.168.100.0/24
      TS_STATE_DIR: /var/lib/tailscale
      TS_HOSTNAME: saturn-1
    image: tailscale/tailscale:latest
    container_name: tailscaled
    deploy:
      resources:
        reservations:
          memory: 32M
    network_mode: host
    restart: unless-stopped
    volumes:
    - /dev/net/tun:/dev/net/tun
    - /DATA/AppData/tailscaled/config:/var/lib/tailscale
