name: transmission-arm
services:
  transmission-arm:
    environment:
      PASS: saturn
      PEERPORT: '51413'
      PGID: '1000'
      PUID: '1000'
      TRANSMISSION_WEB_HOME: /transmission-web-control/
      TZ: Europe/London
      USER: saturn
    image: linuxserver/transmission:arm32v7-4.0.3
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
    - target: 9091
      published: '9091'
      protocol: tcp
    - target: 51413
      published: '51413'
      protocol: tcp
    - target: 51413
      published: '51413'
      protocol: UDP
    restart: unless-stopped
    volumes:
    - type: bind
      source: /DATA/AppData/transmission-arm/config
      target: /config
    - type: bind
      source: /DATA/Downloads
      target: /downloads
    - type: bind
      source: /DATA/Downloads/watch
      target: /watch
    container_name: transmission-arm
