name: surveyking
services:
  surveyking:
    image: surveyking/surveyking:latest
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
    - 1991:1991
    restart: unless-stopped
    volumes:
    - /DATA/AppData/surveyking/db:/app/db
    - /DATA/AppData/surveyking/files:/app/files
    - /DATA/AppData/surveyking/logs:/app/logs
    container_name: surveyking
