version: '3'
name: halo
services:
  halo:
    image: halohub/halo:2
    container_name: halo-app
    deploy:
      resources:
        reservations:
          memory: 512M
    restart: unless-stopped
    depends_on:
      halodb:
        condition: service_healthy
    networks:
    - halo
    volumes:
    - /DATA/AppData/halo2/app:/root/.halo2
    ports:
    - 8090:8090
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8090/actuator/health/readiness
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
    - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
    - --spring.r2dbc.username=halo
    - --spring.r2dbc.password=openpostgresql
    - --spring.sql.init.platform=postgresql
    - --halo.external-url=http://localhost:8090/
  halodb:
    image: postgres:15.4
    container_name: halo-db
    restart: unless-stopped
    networks:
    - halo
    volumes:
    - /DATA/AppData/halo/db:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD
      - pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
    - POSTGRES_PASSWORD=openpostgresql
    - POSTGRES_USER=halo
    - POSTGRES_DB=halo
    - PGUSER=halo
networks:
  halo:
    name: halo
